FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

# Install all dependencies (including dev)
RUN npm install --legacy-peer-deps

COPY . .

# Build using local CLI
RUN npx nest build

EXPOSE 3000

CMD ["node", "dist/main"]
